version: '3'

services:
  prometheus:
    image: prom/prometheus
    expose:
      - 9090
    ports:
      - 9090:9090
    volumes:
      - prometheus:/etc/prometheus


  pushgateway:
    image: prom/pushgateway
    expose:
      - 9091
    ports:
      - 9091:9091