name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule: 
    - cron: '5 4 * * *'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env: 
      BUILDEVENT_FILE: './buildevents.txt' # This is root of our repository
    steps:
    - name: Set start time
      run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - uses: kvrhdn/gha-buildevents@v1
      with:
        apikey: ${{ secrets.BUILD_APIKEYS }}
        dataset: tau-build-pipeline
        job-status: ${{ job.status }}
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Telemetry start - playwright tests
      if: always()
      run: |
        echo "STEP_START=$(date +%s)" >> $GITHUB_ENV
        echo "STEP_ID=run-playwright-tests" >> $GITHUB_ENV  
    - name: Run Playwright tests
      run: npx playwright test
    - name: Set up script permissions
      run: chmod +x reports/test_result_script.sh  
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
    - name: Telemetry - Collect build data
      working-directory: reports
      env: 
        PUSHGATEWAY_URL: ${{ secrets.PUSHGATEWAY_URL}}
        BUILDEVENT_FILE: ./${{ env.BUILDEVENT_FILE }}
      if: always()
      run: |
        echo "github_actions_total_duration $(expr $(date +%s) - ${START_TIME})" | curl --data-binary @- ${PUSHGATEWAY_URL}/metrics/job/github_actions
        ./test_result_script.sh
        buildevents step $TRACE_ID $STEP_ID $STEP_START $STEP_ID
